#!/usr/bin/env bash
# install nginx on your web-01 server
sudo apt-get update
sudo apt-get install -y nginx
sudo systemctl start nginx.service
sudo touch /var/www/html/index.html
sudo echo "Hello World" > /var/www/html/index.html
sudo service nginx restart
