#!/usr/bin/env bash
# install nginx on your web-01 server
sudo apt-get update
sudo apt-get install -y nginx
sudo systemctl start nginx.service
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
mkdir /etc/nginx/sites-enabled/
touch /etc/nginx/sites-enabled/default
echo "server {
       listen 80;
       listen [::]:80;

       server_name megantheeartist.tech;

       root /var/www/html;
       index index.html;
       }
}" > /etc/nginx/sites-enabled/default
sudo service nginx restart