#!/usr/bin/env bash
# install nginx on your web-01 server
sudo apt-get update
sudo apt-get install -y nginx
sudo systemctl start nginx.service
sudo touch /var/www/html/index.html
sudo echo "Hello World" > /var/www/html/index.html
sudo mkdir /etc/nginx/sites-enabled/
sudo touch /etc/nginx/sites-enabled/default
sudo echo "server {
       listen 80;
       listen [::]:80;

       server_name megantheeartist.tech;

       root /var/www/html;
       index index.html;
       }
}" > /etc/nginx/sites-enabled/default
sudo service nginx restart
