#!/usr/bin/env bash
# configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get install -y nginx
sudo systemctl start nginx.service
sudo touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
string="\tlocation /redirect_me {\n\t\t return 301 \$scheme://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@$search@$string@" /etc/nginx/sites-available/default
sudo service nginx restart
