#!/usr/bin/env bash
# configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get install -y nginx
sudo systemctl start nginx.service
sudo touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
find="^\tlocation / {"
string="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://tiktok.com/@meg_grigss?_t=8X3nb1Rj0kV&_r=1;\n\t}\n\n\tlocation / {"
sudo sed -i "s@$find@$string@" /etc/nginx/sites-available/default
sudo service nginx restart
