#!/usr/bin/env bash
# configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get update
sudo apt-get -y install nginx
sudo systemctl start nginx.service
echo "Hello World" | sudo tee /var/www/html/index.html
sudo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
location="\tlocation / {"
replace_error404="\terror_page 404 /error404.html;\n\n\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@^$location@$replace_error404@" /etc/nginx/sites-available/default
sudo service nginx restart
