#!/usr/bin/env bash
# install nginx on your web-01 server
sudo apt-get update
sudo apt-get install -y nginx
sudo systemctl start nginx.service
sudo touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
sudo touch /var/www/html/error.html
echo "Ceci n'est pas une page" > /var/www/html/error.html
error="\n\terror_page 404 \/error.html;\n"
sed -r -i "/^\s+server_name .+;/a\ $error" /etc/nginx/sites-available/default
sed -r -i "/^\s+server_name .+;/a\ $error" /etc/nginx/sites-enabled/default
sudo service nginx restart
