#!/usr/bin/env bash
#prints numbers 1 to 100 and prints "FizzBuzz" for multiples of 3 and 5, and prints "Fizz" for multiples of 3, and prints "Buzz" for multiples of 5
i=1
while [ $i -le 100 ]
do
	if [ $((i%3)) == 0 ] && [ $((i%5)) == 0 ]
	then 
		echo "FizzBuzz"
		((i++))
	elif [ $((i%3)) == 0 ]
	then
		echo "Fizz"
		((i++))
	elif [ $((i%5)) == 0 ]
	then
		echo "Buzz"
		((i++))
	else
		echo "$i"
		((i++))
	fi
done
