#!/usr/bin/env bash
#prints "Best School" while integer is less than or equal to ten and prints "bad luck" when integer is equal to 4 and prints "good luck" when integer is equal to 8
i=1
while [ $i -le 10 ]
do
	if [ $i == 4 ]
	then
		echo "bad luck"
		((i++))
	elif [ $i == 8 ]
	then
		echo "good luck"
		((i++))
	else
		echo "Best School"
		((i++))
	fi
done
