#!/usr/bin/env bash
#prints the integer while integer is less than or equal to 20 and prints "bad luck from China" after integer 4, and prints "bad luck from Japan" after integer 9, and prints "back luck from Italy" after integer 17
i=1
while [ $i -le 20 ]
do
	echo "$i"
	((i++))
	case "$i" in
		5) echo "bad luck from China";;
		10) echo "bad luck from Japan";;
		18) echo "bad luck from Italy";;
esac
done
