#!/usr/bin/env bash
#prints the time for 12 hours and 59 minutes while displaying hours 0 to 12
h=0
while [ $h -le 12 ]
do
	echo "Hour: $h"
	((h++))
	m=1
	while [ $m -le 59 ]
	do
		echo $m
		((m++))
	done
done
