#!/usr/bin/env bash
# configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install nginx
sudo systemctl start nginx.service
echo "Hello World" | sudo tee /var/www/html/index.html
sudo touch /var/www/html/error404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
search1="^\tlocation / {"
string="\tlocation /redirect_me {\n\t\t return 301 \$scheme://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
string2="\terror_page 404 /error404.html;\n\n\tadd_header X-Served-By ${HOSTNAME};\n\n\tlocation / {"
sudo sed -i "s@$search1@$string@" /etc/nginx/sites-enabled/default
sudo sed -i "s@$search1@$string2@" /etc/nginx/sites-enabled/default
sudo service nginx restart
