#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server
sudo apt update
sudo apt install -y haproxy
frontend="frontend myproxy
\n\tbind *:80
\n\tdefault_backend web_servers
\nbackend web_servers
\n\tbalance roundrobin
\n\tserver web-01 54.227.95.34:80 check
\n\tserver web-02 34.224.213.46:80 check"
echo -e "$frontend" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
